const incidents = [
  { id: 'INC-042', title: 'Pine St. Flooding', detail: 'Water rising · 42 people awaiting transport', people: 42, status: 'CRITICAL', type: 'critical', coords: [30.451, -91.187] },
  { id: 'INC-041', title: 'Bridge collapse', detail: 'Access blocked · 12 people trapped', people: 12, status: 'ACTIVE', type: 'active', coords: [30.462, -91.170] },
  { id: 'INC-039', title: 'Shelter East', detail: 'Capacity 64% · 128 people', people: 128, capacity: 200, address: '2250 Florida Blvd, Baton Rouge, Louisiana', status: 'MONITOR', type: 'shelter', coords: [30.440, -91.160] },
  { id: 'INC-037', title: 'Medical staging', detail: 'Medic 04 · 2 available', status: 'RESOURCE', type: 'resource', coords: [30.430, -91.180] }
];
const list = document.querySelector('#incidentList');
const feed = document.querySelector('#activityFeed');
const members = [
  { name: 'Sam Kim', role: 'USAR Technician', cert: 'Rope Rescue', expires: '2027-04-18', availability: 'available' },
  { name: 'Taylor Nguyen', role: 'EMS Lead', cert: 'Wilderness First Responder', expires: '2026-09-02', availability: 'available' },
  { name: 'Jordan Brooks', role: 'Swift Water Team', cert: 'Swiftwater Rescue', expires: '2026-07-30', availability: 'unavailable' },
  { name: 'Morgan Reed', role: 'Transport Driver', cert: 'Emergency Vehicle Operator', expires: '2026-12-11', availability: 'available' }
];
function certificationStatus(member) { const days = (new Date(member.expires) - new Date('2026-08-11')) / 86400000; return days < 0 ? 'expired' : days <= 60 ? 'due' : 'current'; }
function renderCertifications() { const query = (document.querySelector('#memberSearch')?.value || '').toLowerCase(); const filter = document.querySelector('#certFilter')?.value || 'all'; const availability = document.querySelector('#availabilityFilter')?.value || 'all'; const rows = members.filter((member) => `${member.name} ${member.role} ${member.cert}`.toLowerCase().includes(query)).filter((member) => filter === 'all' || certificationStatus(member) === filter).filter((member) => availability === 'all' || member.availability === availability); document.querySelector('#certificationList').innerHTML = rows.map((member) => { const status = certificationStatus(member); const label = status === 'expired' ? 'EXPIRED' : status === 'due' ? 'RENEWAL DUE' : 'CURRENT'; const availabilityLabel = member.availability === 'available' ? 'AVAILABLE' : 'UNAVAILABLE'; const toggleLabel = member.availability === 'available' ? 'Mark unavailable' : 'Mark available'; return `<div class="cert-row"><div><strong>${member.name}</strong><small>${member.role}</small></div><div><strong>${member.cert}</strong><small>Expires ${member.expires}</small></div><button class="availability-button ${member.availability}" data-member="${member.name}" aria-label="${toggleLabel}"><span class="cert-status ${status}">${label}</span><br><em class="availability ${member.availability}">${availabilityLabel}</em><small>${toggleLabel}</small></button><button class="renew-cert" data-member="${member.name}">Renew 1 year</button></div>`; }).join('') || '<div class="board-row"><small>No members match this filter.</small></div>'; document.querySelector('#certSummary').textContent = `${members.length} TRACKED · ${members.filter((member) => member.availability === 'available').length} AVAILABLE`; }
function shelterIncident() { return incidents.find((incident) => incident.type === 'shelter'); }
function updateOperationsBoard() { const shelter = shelterIncident(); const openIncidents = incidents.filter((incident) => incident.status !== 'RESOLVED' && incident.type !== 'shelter').length; const peopleMoving = incidents.filter((incident) => incident.type !== 'shelter').reduce((total, incident) => total + (incident.people || 0), 0); const capacity = shelter ? Math.round((shelter.people / shelter.capacity) * 100) : 0; const openTarget = document.querySelector('#boardOpenIncidents'); if (!openTarget) return; openTarget.textContent = String(openIncidents).padStart(2, '0'); document.querySelector('#boardPeopleMoving').textContent = String(peopleMoving).padStart(2, '0'); document.querySelector('#boardShelterCapacity').textContent = `${capacity}%`; document.querySelector('#boardShelterDetail').textContent = `${shelter?.people || 0} of ${shelter?.capacity || 0} beds used`; document.querySelector('#boardUnitsField').textContent = vehicles.length; document.querySelector('#boardIncidentList').innerHTML = incidents.filter((incident) => incident.type !== 'shelter').map((incident) => `<div class="board-row"><div><strong>${incident.id} · ${incident.title}</strong><small>${incident.detail}</small></div><span class="board-tag ${incident.status === 'RESOLVED' ? 'safe' : ''}">${incident.status}</span></div>`).join(''); document.querySelector('#boardActivity').innerHTML = [...feed.querySelectorAll('.activity-item')].slice(0, 6).map((item) => `<div class="board-row"><div>${item.querySelector('p')?.innerHTML || ''}<small>${item.querySelector('.activity-note')?.textContent || item.querySelector('small')?.textContent || ''}</small></div></div>`).join(''); }
const map = L.map('map', { zoomControl: false }).setView([30.451, -91.180], 14);
L.control.zoom({ position: 'bottomright' }).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
const louisianaResources = L.layerGroup().addTo(map);
async function loadLouisianaResources() { const button = document.querySelector('#loadStateResourcesBtn'); if (button) { button.disabled = true; button.textContent = 'Loading statewide resources...'; } const query = '[out:json][timeout:60];area["ISO3166-2"="US-LA"][admin_level=4]->.searchArea;(nwr["amenity"="fire_station"](area.searchArea);nwr["amenity"="police"](area.searchArea);nwr["amenity"="hospital"](area.searchArea););out center tags;'; try { let response; for (const endpoint of ['https://overpass-api.de/api/interpreter', 'https://overpass.kumi.systems/api/interpreter', 'https://overpass.private.coffee/api/interpreter']) { try { response = await fetch(`${endpoint}?data=${encodeURIComponent(query)}`); if (response.ok) break; } catch (error) { response = null; } } if (!response?.ok) throw new Error('No Overpass endpoint available'); const data = await response.json(); const bounds = []; data.elements.forEach((element) => { const latitude = element.lat ?? element.center?.lat; const longitude = element.lon ?? element.center?.lon; if (latitude == null || longitude == null) return; const amenity = element.tags?.amenity; const kind = amenity === 'fire_station' ? 'FIRE STATION' : amenity === 'police' ? 'POLICE STATION' : 'HOSPITAL'; const color = amenity === 'fire_station' ? '#ef725e' : amenity === 'police' ? '#4f5db3' : '#d39a26'; const name = element.tags?.name || kind; const address = [element.tags?.['addr:housenumber'], element.tags?.['addr:street'], element.tags?.['addr:city']].filter(Boolean).join(' ') || 'Address not listed'; L.circleMarker([latitude, longitude], { radius: 5, color, fillColor: color, fillOpacity: .9, weight: 2 }).bindPopup(`<strong>${name}</strong><br><span class="resource-type">${kind}</span><br><small>${address}</small>`, { autoPan: false }).addTo(louisianaResources); bounds.push([latitude, longitude]); }); if (bounds.length) map.fitBounds(bounds, { padding: [30, 30], maxZoom: 9 }); addActivity('Louisiana resources loaded', `${bounds.length} fire stations, police stations, and hospitals added to the map.`, 'JM', 'teal'); } catch (error) { addActivity('Resource load failed', 'Louisiana statewide resources could not be loaded. Check the network connection.', 'JM', 'coral'); } finally { if (button) { button.disabled = false; button.textContent = 'Reload Louisiana resources'; } } }
const markerStyles = { critical: '#ef725e', active: '#f5ba4d', warning: '#f5ba4d', resource: '#087e7b', shelter: '#8b5bb5', supply: '#c7772d' };
const markers = {};
function markerIcon(type) { return L.divIcon({ className: 'incident-pin', html: `<span style="background:${markerStyles[type]}"></span>`, iconSize: [22, 22], iconAnchor: [11, 11] }); }
const vehicleStyles = { USAR: '#087e7b', 'Swift water': '#2475a8', 'Fire truck': '#ef725e', Police: '#4f5db3', EMS: '#d39a26', Volunteer: '#8b5bb5', 'Transport small': '#6a7d82', 'Transport medium': '#48656a', 'Transport large': '#29494f', 'Helicopter crew': '#c7772d' };
function vehicleIcon(type) { const symbol = type === 'EMS' ? '+' : type === 'Helicopter crew' ? '✦' : type === 'Volunteer' ? '♥' : type.startsWith('Transport') ? '▰' : '▰'; return L.divIcon({ className: 'vehicle-pin', html: `<span style="background:${vehicleStyles[type] || vehicleStyles.USAR}">${symbol}</span>`, iconSize: [24, 24], iconAnchor: [12, 12] }); }
const vehicles = [
  { id: 'USAR 01', type: 'USAR', position: [30.438, -91.204], target: [30.451, -91.187], progress: .22 },
  { id: 'SWIFT 02', type: 'Swift water', position: [30.475, -91.170], target: [30.451, -91.187], progress: .34 },
  { id: 'ENGINE 07', type: 'Fire truck', position: [30.425, -91.158], target: [30.462, -91.170], progress: .12 },
  { id: 'POLICE 12', type: 'Police', position: [30.448, -91.220], target: [30.462, -91.170], progress: .48 },
  { id: 'MEDIC 04', type: 'EMS', position: [30.414, -91.181], target: [30.430, -91.180], progress: .62 },
  { id: 'VOLUNTEER 08', type: 'Volunteer', position: [30.432, -91.198], target: [30.440, -91.160], progress: .18 },
  { id: 'SHUTTLE 12', type: 'Transport small', capacity: 4, driverSeats: 1, volunteerSeats: 3, position: [30.440, -91.160], target: [30.451, -91.187], progress: .40 },
  { id: 'BUS 03', type: 'Transport medium', capacity: 16, driverSeats: 1, volunteerSeats: 15, position: [30.440, -91.160], target: [30.430, -91.180], progress: .26 },
  { id: 'COACH 01', type: 'Transport large', capacity: 40, driverSeats: 1, volunteerSeats: 39, position: [30.440, -91.160], target: [30.462, -91.170], progress: .12 },
  { id: 'AIR 01', type: 'Helicopter crew', position: [30.485, -91.205], target: [30.451, -91.187], progress: .55 }
];
async function loadRoadRoute(vehicle) { const start = vehicle.routeStart || vehicle.position; const end = vehicle.target; try { const response = await fetch(`https://router.project-osrm.org/route/v1/driving/${start[1]},${start[0]};${end[1]},${end[0]}?overview=full&geometries=geojson`); const data = await response.json(); const coordinates = data.routes?.[0]?.geometry?.coordinates || []; vehicle.route = coordinates.map(([longitude, latitude]) => [latitude, longitude]); } catch (error) { vehicle.route = [start, end]; } vehicle.progress = 0; }
function escapeVehicleName(name) { return name.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]); }
function vehiclePopup(vehicle) { const displayName = vehicle.name ? escapeVehicleName(vehicle.name) : 'No custom name'; const capacity = vehicle.capacity ? `<div class="vehicle-capacity"><strong>${vehicle.capacity} total seats</strong><br>1 driver · ${vehicle.volunteerSeats} volunteer/passenger seats</div>` : ''; return `<strong>${vehicle.id}</strong><br>${vehicle.type}${capacity}<br><span class="vehicle-name">Name: ${displayName}</span><br><input class="vehicle-name-input" value="${vehicle.name ? escapeVehicleName(vehicle.name) : ''}" placeholder="Enter unit name"><button class="save-vehicle-name" data-vehicle="${vehicle.id}">Save name</button> <button class="clear-vehicle-name" data-vehicle="${vehicle.id}">Delete name</button><br><label class="return-label">RETURN TO<select class="return-destination" data-vehicle="${vehicle.id}"><option value="staging">Shelter East staging</option><option value="fob">FOB</option><option value="boo">BOO</option><option value="home">Home agency</option><option value="firehouse">Fire house</option></select></label><button class="return-vehicle" data-vehicle="${vehicle.id}">↩ Send unit</button>`; }
vehicles.forEach((vehicle) => { vehicle.staging = [30.440, -91.160]; vehicle.route = [vehicle.position, vehicle.target]; vehicle.marker = L.marker(vehicle.position, { icon: vehicleIcon(vehicle.type) }).addTo(map).bindTooltip(`${vehicle.name || vehicle.id} · en route`, { direction: 'top', offset: [0, -10] }); vehicle.marker.bindPopup(vehiclePopup(vehicle), { autoPan: false }); vehicle.marker.on('popupopen', () => { vehicle.popupOpen = true; const saveButton = document.querySelector(`.save-vehicle-name[data-vehicle="${vehicle.id}"]`); const clearButton = document.querySelector(`.clear-vehicle-name[data-vehicle="${vehicle.id}"]`); const returnButton = document.querySelector(`.return-vehicle[data-vehicle="${vehicle.id}"]`); if (saveButton) saveButton.addEventListener('click', () => { vehicle.name = document.querySelector('.vehicle-name-input').value.trim(); vehicle.marker.setTooltipContent(`${vehicle.name || vehicle.id} · en route`); vehicle.marker.setPopupContent(vehiclePopup(vehicle)); vehicle.marker.openPopup(); addActivity('Unit name updated', `${vehicle.id} is now named ${vehicle.name || 'unnamed'}.`, 'JM', 'coral'); }); if (clearButton) clearButton.addEventListener('click', () => { vehicle.name = ''; vehicle.marker.setTooltipContent(`${vehicle.id} · en route`); vehicle.marker.setPopupContent(vehiclePopup(vehicle)); vehicle.marker.openPopup(); addActivity('Unit name deleted', `${vehicle.id} custom name removed.`, 'JM', 'coral'); }); if (returnButton) returnButton.addEventListener('click', () => { const destination = document.querySelector(`.return-destination[data-vehicle="${vehicle.id}"]`).value; const targets = { staging: vehicle.staging, fob: baseMarkers.fob?.getLatLng() || [30.455, -91.205], boo: baseMarkers.boo?.getLatLng() || [30.475, -91.145], home: [30.415, -91.145], firehouse: [30.455, -91.145] }; const labels = { staging: 'Shelter East staging', fob: 'FOB', boo: 'BOO', home: 'home agency', firehouse: 'fire house' }; const target = targets[destination]; const current = vehicle.marker.getLatLng(); vehicle.routeStart = [current.lat, current.lng]; vehicle.target = [target.lat || target[0], target.lng || target[1]]; vehicle.marker.setTooltipContent(`${vehicle.name || vehicle.id} · returning to ${labels[destination]}`); loadRoadRoute(vehicle); addActivity('Vehicle sent home', `${vehicle.name || vehicle.id} is returning to ${labels[destination]}.`, 'JM', 'coral'); }); }); vehicle.marker.on('popupclose', () => { vehicle.popupOpen = false; }); loadRoadRoute(vehicle); });
document.addEventListener('click', (event) => { const clearButton = event.target.closest('.clear-vehicle-name'); if (!clearButton || event.defaultPrevented) return; const vehicle = vehicles.find((item) => item.id === clearButton.dataset.vehicle); if (!vehicle) return; vehicle.name = ''; vehicle.marker.setTooltipContent(`${vehicle.id} · en route`); vehicle.marker.setPopupContent(vehiclePopup(vehicle)); vehicle.marker.openPopup(); addActivity('Unit name deleted', `${vehicle.id} custom name removed.`, 'JM', 'coral'); });
setInterval(() => { vehicles.forEach((vehicle) => { if (vehicle.popupOpen || !vehicle.route?.length) return; vehicle.progress += .003; if (vehicle.progress > 1) vehicle.progress = 0; const routeIndex = Math.min(Math.floor(vehicle.progress * (vehicle.route.length - 1)), vehicle.route.length - 1); vehicle.marker.setLatLng(vehicle.route[routeIndex]); }); }, 1000);
function deleteResolvedIncident(id) { const index = incidents.findIndex((incident) => incident.id === id); if (index < 0 || incidents[index].status !== 'RESOLVED') return; const [removed] = incidents.splice(index, 1); if (markers[id]) { markers[id].remove(); delete markers[id]; } renderIncidents(); document.querySelector('#incidentCount').textContent = String(incidents.length).padStart(2, '0'); addActivity('Resolved incident deleted', `${removed.id} · ${removed.title} removed from the exercise.`, 'JM', 'coral'); }
function renderIncidents() {
  Object.values(markers).forEach((marker) => marker.remove());
  list.innerHTML = incidents.map((incident, index) => `<article class="incident ${incident.type} ${index === 0 ? 'selected' : ''}" data-id="${incident.id}"><div class="incident-top"><span class="incident-id">${incident.id}</span><span class="status ${incident.type === 'warning' ? 'amber' : incident.type === 'resource' ? 'green' : ''}">${incident.status}</span></div><h3>${incident.title}</h3><p>${incident.type === 'shelter' ? `Capacity ${Math.round((incident.people / incident.capacity) * 100)}% · ${incident.people} people` : incident.detail}</p>${incident.type === 'shelter' ? `<div class="location-row"><span>${incident.address || 'Map location'}</span><button class="move-location" data-id="${incident.id}">Move</button></div>` : ''}${incident.status === 'RESOLVED' ? `<button class="delete-incident" data-id="${incident.id}">Delete resolved incident</button>` : ''}</article>`).join('');
  incidents.forEach((incident) => {
    const deleteAction = incident.status === 'RESOLVED' ? `<br><button class="delete-incident" data-id="${incident.id}">Delete resolved incident</button>` : '';
    const marker = L.marker(incident.coords, { icon: markerIcon(incident.type) }).addTo(map).bindPopup(`<strong>${incident.id}</strong><br>${incident.title}<br><small>${incident.detail}${incident.address ? `<br>${incident.address}` : ''}</small>${deleteAction}`, { autoPan: false });
    markers[incident.id] = marker;
  });
  list.querySelectorAll('.incident').forEach((card) => card.addEventListener('click', (event) => { if (event.target.closest('.move-location')) return; list.querySelectorAll('.incident').forEach((item) => item.classList.remove('selected')); card.classList.add('selected'); markers[card.dataset.id].openPopup(); map.flyTo(markers[card.dataset.id].getLatLng(), 15, { duration: .6 }); }));
  list.querySelectorAll('.move-location').forEach((button) => button.addEventListener('click', () => { const incident = incidents.find((item) => item.id === button.dataset.id); document.body.classList.add('moving-location'); map.once('click', (event) => { incident.coords = [event.latlng.lat, event.latlng.lng]; incident.address = 'Map position updated'; renderIncidents(); addActivity('Shelter moved', `${incident.title} moved to a new map position.`, 'JM', 'coral'); }); }));
  list.querySelectorAll('.delete-incident').forEach((button) => button.addEventListener('click', () => deleteResolvedIncident(button.dataset.id)));
}
renderIncidents();
document.querySelector('#addIncidentBtn').addEventListener('click', () => {
  const modal = document.createElement('div');
  modal.className = 'location-modal';
  modal.innerHTML = '<form class="location-form"><span class="eyebrow">ADD TO LIVE MAP</span><h2>New incident or site</h2><label>LOCATION TYPE<select id="newLocationType"><option value="incident">Incident</option><option value="shelter">Shelter</option><option value="supply">Supply site</option></select></label><label>NAME<input id="newLocationName" required placeholder="e.g. North parish shelter"></label><label>ADDRESS <span class="optional">(optional)</span><input id="newLocationAddress" placeholder="Street, city, Louisiana"></label><label>DETAILS<input id="newLocationDetail" required placeholder="What should teams know?"></label><label>MAP POSITION<select id="newLocationPosition"><option value="center">Use current map center</option><option value="shelter">Shelter East area</option><option value="flood">Pine St. Flooding area</option><option value="medical">Medical staging area</option></select></label><div class="location-form-actions"><button type="button" class="location-cancel">Cancel</button><button class="location-save">Add to map</button></div></form>';
  document.body.append(modal);
  modal.querySelector('.location-cancel').addEventListener('click', () => modal.remove());
  modal.querySelector('form').addEventListener('submit', async (event) => {
    event.preventDefault();
    const type = modal.querySelector('#newLocationType').value;
    const positionChoice = modal.querySelector('#newLocationPosition').value;
    const positionMap = { center: map.getCenter(), shelter: incidents.find((item) => item.id === 'INC-039').coords, flood: incidents.find((item) => item.id === 'INC-042').coords, medical: incidents.find((item) => item.id === 'INC-037').coords };
    let position = positionMap[positionChoice];
    const id = `SITE-${String(incidents.length + 1).padStart(3, '0')}`;
    const title = modal.querySelector('#newLocationName').value.trim();
    const detail = modal.querySelector('#newLocationDetail').value.trim();
    const typeLabel = type === 'incident' ? 'ACTIVE' : type === 'shelter' ? 'SHELTER' : 'SUPPLY';
    const address = modal.querySelector('#newLocationAddress').value.trim();
    if (address) { try { const response = await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(address)}`); const results = await response.json(); if (results[0]) position = [Number(results[0].lat), Number(results[0].lon)]; } catch (error) { /* Keep the selected fallback position when geocoding is unavailable. */ } }
    incidents.push({ id, title, detail, address, status: typeLabel, type: type === 'incident' ? 'active' : type, coords: [position.lat || position[0], position.lng || position[1]] });
    renderIncidents();
    document.querySelector('#incidentCount').textContent = String(incidents.length).padStart(2, '0');
    addActivity('New ' + type + ' added', `${title}: ${detail}`, 'JM', 'coral');
    modal.remove();
  });
});
const unitDispatch = document.createElement('div');
unitDispatch.className = 'unit-dispatch';
unitDispatch.innerHTML = '<div class="dispatch-title"><label>STUDENT DISPATCH</label><span>ASSIGN A UNIT</span></div><div class="unit-types"><button class="unit-type selected" data-unit="USAR"><span>▣</span>USAR</button><button class="unit-type" data-unit="Swift water"><span>≈</span>SWIFT WATER</button><button class="unit-type" data-unit="Fire truck"><span>◇</span>FIRE</button><button class="unit-type" data-unit="Police"><span>⌁</span>POLICE</button><button class="unit-type" data-unit="EMS"><span>+</span>EMS</button><button class="unit-type" data-unit="Volunteer"><span>♥</span>VOLUNTEER</button><button class="unit-type" data-unit="Transport small"><span>▱</span>SMALL TRANSIT</button><button class="unit-type" data-unit="Transport medium"><span>▰</span>MEDIUM BUS</button><button class="unit-type" data-unit="Transport large"><span>▰</span>LARGE BUS</button><button class="unit-type" data-unit="Helicopter crew"><span>✦</span>HELICOPTER</button></div><div class="dispatch-fields"><label>DESTINATION<select id="unitDestination"><option value="INC-042">INC-042 · Pine St. Flooding</option><option value="INC-041">INC-041 · Bridge collapse</option><option value="INC-039">INC-039 · Shelter East</option><option value="INC-037">INC-037 · Medical staging</option></select></label><label>TEAM SIZE<select id="teamSize"><option>1 unit</option><option>2 units</option><option>3 units</option><option>4 units</option></select></label></div><button class="assign-button" id="assignBtn">Dispatch selected team <span>↗</span></button>';
document.querySelector('.dispatch-box').before(unitDispatch);
unitDispatch.hidden = true;
const instructorControls = document.createElement('div');
instructorControls.className = 'scenario-controls';
instructorControls.innerHTML = '<div class="dispatch-title"><label>INSTRUCTOR UPDATE</label><span>SCENARIO CONTROL</span></div><div class="dispatch-fields"><label>INCIDENT<select id="updateDestination"><option value="INC-042">INC-042 · Pine St. Flooding</option><option value="INC-041">INC-041 · Bridge collapse</option><option value="INC-039">INC-039 · Shelter East</option><option value="INC-037">INC-037 · Medical staging</option></select></label><label>STATUS<select id="updateStatus"><option value="WORSENING">WORSENING</option><option value="STABILIZING">STABILIZING</option><option value="RESOLVED">RESOLVED</option></select></label></div><div class="collapse-controls"><div class="dispatch-title"><label>BUILDING COLLAPSE</label><span>RESCUE COUNT</span></div><div class="dispatch-fields"><label>PEOPLE TRAPPED<input id="trappedCount" type="number" min="0" value="12"></label><button class="assign-button" id="saveTrappedBtn">Update trapped count</button></div><button class="assign-button" id="transportPatientBtn">EMS transport 1 patient <span>↗</span></button></div><textarea id="instructorNote" rows="2" placeholder="What changed at the scene?"></textarea><button class="assign-button" id="postUpdateBtn">Post scenario update <span>↗</span></button><div class="map-tools-title">MAP HAZARDS & BASES</div><div class="map-tools"><button class="map-action" id="closeStreetBtn">╳ Place street closure</button><button class="map-action" id="highWaterBtn">≈ Draw high water</button><button class="map-action" id="ccpBtn">✚ Place CCP point</button><button class="map-action" id="booBtn">BOO Place base</button><button class="map-action" id="fobBtn">FOB Place base</button></div><button class="state-resource-button" id="loadStateResourcesBtn">Load Louisiana resources</button><p class="map-tool-hint" id="mapToolHint">Choose a tool, then click the map.</p>';
document.querySelector('.dispatch-box').before(instructorControls);
const studentRequest = document.createElement('div');
studentRequest.className = 'student-request';
studentRequest.hidden = true;
studentRequest.innerHTML = '<div class="dispatch-title"><label>NEED MORE SUPPORT?</label><span>REQUEST FROM INSTRUCTOR</span></div><div class="dispatch-fields"><label>UNIT TYPE<select id="requestUnit"><option>USAR</option><option>Swift water</option><option>Fire truck</option><option>Police</option><option>EMS</option><option>Volunteer</option><option>Transport small</option><option>Transport medium</option><option>Transport large</option><option>Helicopter crew</option></select></label><label>AMOUNT<select id="requestAmount"><option>1 unit</option><option>2 units</option><option>3 units</option><option>4 units</option></select></label></div><textarea id="requestNote" rows="2" placeholder="Why does your team need support?"></textarea><button class="send-button" id="requestBtn">Request additional units <span>↗</span></button>';
document.querySelector('.dispatch-box').before(studentRequest);
const unitMovement = document.createElement('div');
unitMovement.className = 'unit-movement';
unitMovement.hidden = true;
unitMovement.innerHTML = '<div class="dispatch-title"><label>UNIT MOVEMENT</label><span>SCENE ↔ STAGING</span></div><label class="movement-label">SELECT LIVE UNIT<select id="movementUnit"></select></label><div class="dispatch-fields"><label>MOVE TO SCENE<select id="movementDestination"><option value="INC-042">INC-042 · Pine St. Flooding</option><option value="INC-041">INC-041 · Bridge collapse</option><option value="INC-039">INC-039 · Shelter East</option><option value="INC-037">INC-037 · Medical staging</option></select></label><button class="return-button" id="returnStagingBtn">↩ Return to staging</button></div><button class="assign-button" id="sendSceneBtn">Send unit to scene <span>↗</span></button><div class="evacuation-box"><div class="dispatch-title"><label>MOVE PEOPLE TO SHELTER</label><span>TRANSPORT</span></div><div class="dispatch-fields"><label>FROM INCIDENT<select id="evacuationSource"><option value="INC-042">Pine St. Flooding · 42 people</option><option value="INC-041">Bridge collapse</option></select></label><label>PEOPLE<select id="evacuationCount"><option>5</option><option>10</option><option>20</option><option>All remaining</option></select></label></div><button class="assign-button" id="evacuateBtn">Send people to Shelter East <span>↗</span></button></div><div class="map-tools-title">FIELD BASES</div><div class="map-tools"><button class="map-action" id="studentBooBtn">BOO Place base</button><button class="map-action" id="studentFobBtn">FOB Place base</button></div><p class="map-tool-hint">Place a base, then drag its icon on the map.</p>';
document.querySelector('.dispatch-box').before(unitMovement);
const injectedStyles = document.createElement('style');
injectedStyles.textContent = '.scenario-controls,.student-request,.unit-movement{border-top:1px solid var(--line);padding:14px 0 13px}.scenario-controls textarea,.student-request textarea{margin:0 0 8px}.scenario-controls .dispatch-fields,.student-request .dispatch-fields,.unit-movement .dispatch-fields{margin:8px 0}.scenario-controls .assign-button{background:var(--teal)}.scenario-controls .assign-button:hover{background:var(--teal-dark)}.student-request .send-button{width:100%}.movement-label{display:block;color:var(--muted);font-size:8px;letter-spacing:1px;font-weight:700}.movement-label select,.unit-movement .dispatch-fields select{display:block;width:100%;border:1px solid var(--line);background:white;color:var(--ink);padding:7px 4px;margin-top:4px;font:10px "DM Sans"}.return-button{border:1px solid var(--teal);background:white;color:var(--teal);font-size:9px;font-weight:700;cursor:pointer;margin-top:15px;padding:7px 5px}.return-button:hover{background:#eaf5f1}.map-tools-title{border-top:1px solid var(--line);margin-top:13px;padding-top:12px;color:var(--muted);font-size:8px;letter-spacing:1px;font-weight:700}.map-tools{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:8px}.map-action{border:1px solid var(--line);background:white;color:var(--teal);padding:8px 4px;font-size:9px;font-weight:700;cursor:pointer}.map-action.active{background:#eaf5f1;border-color:var(--teal)}.map-tool-hint{color:var(--muted);font-size:9px;margin:7px 0 0}.closure-pin span{display:grid;place-items:center;width:24px;height:24px;background:#273b40;border:2px solid white;border-radius:50%;color:white;font-weight:700}.water-zone{fill:#338eaf;fill-opacity:.28;stroke:#2475a8;stroke-width:3;stroke-dasharray:8 5}.water-handle,.water-resize-handle{display:grid;place-items:center;width:24px;height:24px;border:2px solid white;border-radius:50%;color:white;font-weight:700}.water-handle{background:#2475a8}.water-resize-handle{background:#075e61;cursor:nwse-resize}.base-pin span{display:grid;place-items:center;min-width:32px;height:25px;padding:0 5px;background:#123d42;border:2px solid white;border-radius:4px;color:white;font:700 10px "DM Sans";box-shadow:0 2px 7px #263b3a66}.boo-pin span{background:#087e7b}.fob-pin span{background:#c7772d}';
document.head.append(injectedStyles);
const capacityStyles = document.createElement('style');
capacityStyles.textContent = '.vehicle-capacity{background:#eef6f3;border-left:3px solid var(--teal);padding:6px 8px;margin:6px 0;font-size:10px;color:var(--muted)}.vehicle-capacity strong{color:var(--teal);font-size:11px}.collapse-controls{border-top:1px solid var(--line);margin-top:12px;padding-top:12px}.collapse-controls input{display:block;width:100%;border:1px solid var(--line);padding:7px;margin-top:4px;font:10px "DM Sans"}.ccp-pin span{display:grid;place-items:center;width:42px;height:25px;background:#d39a26;border:2px solid white;border-radius:4px;color:white;font:700 10px "DM Sans";box-shadow:0 2px 7px #263b3a66}.state-resource-button{width:100%;border:1px solid var(--teal);background:#eef6f3;color:var(--teal);padding:9px;margin-top:10px;font-size:9px;font-weight:700;cursor:pointer}.state-resource-button:disabled{opacity:.65}.resource-type{font-size:9px;color:var(--teal);font-weight:700;letter-spacing:.5px}';
document.head.append(capacityStyles);
function addActivity(label, detail, avatar = 'JM', color = 'coral') { const item = document.createElement('article'); item.className = 'activity-item'; item.innerHTML = `<span class="activity-avatar ${color}">${avatar}</span><div><p><strong>${label}</strong></p><small>Just now · All teams</small><div class="activity-note">${detail.replace(/[<>]/g, '')}</div></div>`; feed.prepend(item); updateOperationsBoard(); }
const replies = [{ from: 'Taylor Nguyen', channel: 'SMS', text: 'EMS 04 checked in and ready.', time: '2 min ago' }, { from: 'Jordan Brooks', channel: 'Email', text: 'Unavailable until 1800. Certification renewal submitted.', time: '8 min ago' }];
function renderReplies() { const target = document.querySelector('#replyInbox'); if (!target) return; target.innerHTML = replies.map((reply) => `<div class="reply-item"><span class="reply-channel">${reply.channel}</span><div><strong>${reply.from}</strong><p>${reply.text}</p><small>${reply.time}</small></div></div>`).join(''); }
function sendAdminAlert() { const message = document.querySelector('#alertMessage').value.trim(); if (!message) return; const audience = document.querySelector('#alertAudience').value; const priority = document.querySelector('#alertPriority').value; const channels = ['sendInApp', 'sendSms', 'sendEmail'].filter((id) => document.querySelector(`#${id}`).checked).map((id) => id === 'sendInApp' ? 'In-app' : id === 'sendSms' ? 'SMS' : id === 'sendEmail' ? 'Email'); const alert = document.createElement('div'); alert.className = `sent-alert ${priority}`; alert.innerHTML = `<strong>${priority.toUpperCase()} · ${audience}</strong><span>${message.replace(/[<>]/g, '')}</span><small>Sent now · ${channels.join(', ') || 'No delivery channel selected'}</small>`; document.querySelector('#sentAlerts').append(alert); addActivity('Admin sent alert', `${priority.toUpperCase()} alert to ${audience}: ${message}`, 'AD', 'coral'); document.querySelector('#alertMessage').value = ''; } const payments = []; function renderPaymentLog() { const target = document.querySelector('#paymentLog'); if (!target) return; target.innerHTML = payments.length ? payments.map((payment) => `<div class="payment-entry"><div><strong>${payment.recipient}</strong><small>${payment.purpose}</small></div><div><span class="payment-status ${payment.status.toLowerCase()}">${payment.status}</span><small>${payment.token}</small></div></div>`).join('') : '<div class="board-row"><small>No payment requests yet.</small></div>'; } function sendPaymentRequest() { const recipient = document.querySelector('#paymentRecipient').value.trim(); const amountValue = document.querySelector('#paymentAmount').value.trim(); const purpose = document.querySelector('#paymentPurpose').value.trim(); const token = document.querySelector('#paymentToken').value.trim(); const phone = document.querySelector('#paymentPhone').value.trim(); const email = document.querySelector('#paymentEmail').value.trim(); if (!recipient || !amountValue || !purpose || !token) return; const payment = { recipient, amount: `$${Number(amountValue).toFixed(2)}`, purpose: purpose.replace(/[<>]/g, ''), token, phone, email, status: 'Pending' }; payments.unshift(payment); renderPaymentLog(); addActivity('Payment request logged', `${payment.recipient} · ${payment.amount} · ${payment.status}`, 'PM', 'teal'); document.querySelector('#paymentForm').reset(); setTimeout(() => { payment.status = Math.random() > 0.15 ? 'Sent' : 'Failed'; renderPaymentLog(); addActivity(`Payment ${payment.status.toLowerCase()}`, `${payment.recipient} · ${payment.amount} · ${payment.token}`, 'PM', payment.status === 'Sent' ? 'teal' : 'coral'); }, 1400); } document.querySelector('#paymentForm')?.addEventListener('submit', (event) => { event.preventDefault(); sendPaymentRequest(); }); document.querySelector('#paymentSendBtn')?.addEventListener('click', sendPaymentRequest); let activeMapTool = null;
let activeMapTool = null;
let highWaterZone = null;
let highWaterMoveHandle = null;
let highWaterResizeHandle = null;
const baseMarkers = {};
let ccpMarker = null;
function armMapTool(tool, button, hint) { activeMapTool = tool; document.querySelectorAll('.map-action').forEach((item) => item.classList.remove('active')); button.classList.add('active'); document.querySelector('#mapToolHint').textContent = hint; }
document.querySelector('#closeStreetBtn').addEventListener('click', (event) => armMapTool('closure', event.currentTarget, 'Click the map where the street is closed.'));
document.querySelector('#highWaterBtn').addEventListener('click', (event) => armMapTool('water', event.currentTarget, 'Click the map to place a movable high-water zone.'));
document.querySelector('#ccpBtn').addEventListener('click', (event) => armMapTool('ccp', event.currentTarget, 'Click the map to place the draggable CCP point.'));
document.querySelector('#booBtn').addEventListener('click', (event) => armMapTool('boo', event.currentTarget, 'Click the map to place the draggable BOO.'));
document.querySelector('#fobBtn').addEventListener('click', (event) => armMapTool('fob', event.currentTarget, 'Click the map to place the draggable FOB.'));
document.querySelector('#loadStateResourcesBtn').addEventListener('click', loadLouisianaResources);
document.querySelector('#studentBooBtn').addEventListener('click', (event) => armMapTool('boo', event.currentTarget, 'Click the map to place the draggable BOO.'));
document.querySelector('#studentFobBtn').addEventListener('click', (event) => armMapTool('fob', event.currentTarget, 'Click the map to place the draggable FOB.'));
map.on('click', (event) => {
  if (activeMapTool === 'closure') {
    const marker = L.marker(event.latlng, { icon: L.divIcon({ className: 'closure-pin', html: '<span>╳</span>', iconSize: [24, 24], iconAnchor: [12, 12] }) }).addTo(map).bindPopup('<strong>STREET CLOSED</strong><br>Instructor hazard marker<br><button class="delete-map-icon">Delete closure</button>', { autoPan: false });
    marker.on('popupopen', () => { const deleteButton = document.querySelector('.delete-map-icon'); if (deleteButton) deleteButton.addEventListener('click', () => { marker.remove(); addActivity('Instructor deleted street closure', 'Street closure removed from the map.', 'JM', 'coral'); }); });
    marker.openPopup();
    addActivity('Instructor placed street closure', `Road closed at ${event.latlng.lat.toFixed(4)}, ${event.latlng.lng.toFixed(4)}.`, 'JM', 'coral');
  }
  if (activeMapTool === 'water') {
    if (highWaterZone) highWaterZone.remove();
    if (highWaterMoveHandle) highWaterMoveHandle.remove();
    if (highWaterResizeHandle) highWaterResizeHandle.remove();
    const size = .0025;
    highWaterZone = L.rectangle([[event.latlng.lat - size, event.latlng.lng - size], [event.latlng.lat + size, event.latlng.lng + size]], { className: 'water-zone', color: '#2475a8', fillColor: '#338eaf', fillOpacity: .28, weight: 3, dashArray: '8 5' }).addTo(map).bindPopup('<strong>HIGH WATER</strong><br>Drag the center handle to move it. Drag the corner handle to resize it.<br><button class="delete-water-zone">Delete high water</button>', { autoPan: false }).openPopup();
    highWaterMoveHandle = L.marker(event.latlng, { icon: L.divIcon({ className: 'water-handle', html: '<span>≈</span>', iconSize: [24, 24], iconAnchor: [12, 12] }), draggable: true }).addTo(map);
    highWaterResizeHandle = L.marker([event.latlng.lat + size, event.latlng.lng + size], { icon: L.divIcon({ className: 'water-resize-handle', html: '<span>↘</span>', iconSize: [24, 24], iconAnchor: [12, 12] }), draggable: true }).addTo(map);
    highWaterMoveHandle.on('drag', (dragEvent) => { const center = highWaterMoveHandle.getLatLng(); const bounds = highWaterZone.getBounds(); const oldCenter = bounds.getCenter(); const deltaLat = center.lat - oldCenter.lat; const deltaLng = center.lng - oldCenter.lng; highWaterZone.setBounds([[bounds.getSouth() + deltaLat, bounds.getWest() + deltaLng], [bounds.getNorth() + deltaLat, bounds.getEast() + deltaLng]]); highWaterResizeHandle.setLatLng([highWaterResizeHandle.getLatLng().lat + deltaLat, highWaterResizeHandle.getLatLng().lng + deltaLng]); });
    highWaterMoveHandle.on('dragend', () => { const finalPosition = highWaterMoveHandle.getLatLng(); addActivity('Instructor moved high-water zone', `High water moved to ${finalPosition.lat.toFixed(4)}, ${finalPosition.lng.toFixed(4)}.`, 'JM', 'coral'); });
    highWaterResizeHandle.on('drag', () => { const center = highWaterMoveHandle.getLatLng(); const corner = highWaterResizeHandle.getLatLng(); const height = Math.max(.0008, Math.abs(corner.lat - center.lat)); const width = Math.max(.0008, Math.abs(corner.lng - center.lng)); highWaterZone.setBounds([[center.lat - height, center.lng - width], [center.lat + height, center.lng + width]]); });
    highWaterResizeHandle.on('dragend', () => { const bounds = highWaterZone.getBounds(); addActivity('Instructor resized high-water zone', `High water area is now ${(bounds.getNorth() - bounds.getSouth()).toFixed(4)}° tall by ${(bounds.getEast() - bounds.getWest()).toFixed(4)}° wide.`, 'JM', 'coral'); });
    highWaterZone.on('popupopen', () => { const deleteButton = document.querySelector('.delete-water-zone'); if (deleteButton) deleteButton.addEventListener('click', () => { highWaterZone.remove(); highWaterMoveHandle.remove(); highWaterResizeHandle.remove(); highWaterZone = null; highWaterMoveHandle = null; highWaterResizeHandle = null; addActivity('Instructor deleted high water', 'High-water block removed from the map.', 'JM', 'coral'); }); });
    addActivity('Instructor marked high water', 'A movable high-water zone was added to the map.', 'JM', 'coral');
  }
  if (activeMapTool === 'boo' || activeMapTool === 'fob') {
    const baseType = activeMapTool;
    const label = baseType.toUpperCase();
    if (baseMarkers[baseType]) baseMarkers[baseType].remove();
    const marker = L.marker(event.latlng, { icon: L.divIcon({ className: `base-pin ${baseType}-pin`, html: `<span>${label}</span>`, iconSize: [42, 29], iconAnchor: [21, 14] }), draggable: true }).addTo(map).bindPopup(`<strong>${label}</strong><br>Drag this base to move it.<br><button class="delete-base" data-base="${baseType}">Delete ${label}</button>`, { autoPan: false }).openPopup();
    baseMarkers[baseType] = marker;
    marker.on('popupopen', () => { const deleteButton = document.querySelector(`.delete-base[data-base="${baseType}"]`); if (deleteButton) deleteButton.addEventListener('click', () => { marker.remove(); delete baseMarkers[baseType]; addActivity(`Instructor deleted ${label}`, `${label} removed from the map.`, 'JM', 'coral'); }); });
    marker.on('dragend', () => { const position = marker.getLatLng(); addActivity(`Instructor moved ${label}`, `${label} moved to ${position.lat.toFixed(4)}, ${position.lng.toFixed(4)}.`, 'JM', 'coral'); });
    addActivity(`Instructor placed ${label}`, `${label} added to the map.`, 'JM', 'coral');
  }
  if (activeMapTool === 'ccp') {
    if (ccpMarker) ccpMarker.remove();
    ccpMarker = L.marker(event.latlng, { icon: L.divIcon({ className: 'ccp-pin', html: '<span>CCP</span>', iconSize: [42, 28], iconAnchor: [21, 14] }), draggable: true }).addTo(map).bindPopup('<strong>CCP · Casualty Collection Point</strong><br>Drag to move this medical collection point.<br><button class="delete-ccp">Delete CCP</button>', { autoPan: false }).openPopup();
    ccpMarker.on('dragend', () => { const position = ccpMarker.getLatLng(); addActivity('Instructor moved CCP', `CCP moved to ${position.lat.toFixed(4)}, ${position.lng.toFixed(4)}.`, 'JM', 'coral'); });
    ccpMarker.on('popupopen', () => { const deleteButton = document.querySelector('.delete-ccp'); if (deleteButton) deleteButton.addEventListener('click', () => { ccpMarker.remove(); ccpMarker = null; addActivity('Instructor deleted CCP', 'Casualty Collection Point removed from the map.', 'JM', 'coral'); }); });
    addActivity('Instructor placed CCP', 'Casualty Collection Point added for EMS operations.', 'JM', 'coral');
  }
  if (activeMapTool) { activeMapTool = null; document.querySelectorAll('.map-action').forEach((item) => item.classList.remove('active')); document.querySelector('#mapToolHint').textContent = 'Choose a tool, then click the map.'; }
});
const movementUnit = document.querySelector('#movementUnit');
movementUnit.innerHTML = vehicles.map((vehicle) => `<option value="${vehicle.id}">${vehicle.id} · ${vehicle.type}</option>`).join('');
function moveUnit(target, label) { const vehicle = vehicles.find((item) => item.id === movementUnit.value); const current = vehicle.marker.getLatLng(); vehicle.routeStart = [current.lat, current.lng]; vehicle.target = target; vehicle.progress = 0; vehicle.marker.setTooltipContent(`${vehicle.id} · ${label}`); addActivity('Student moved unit', `${vehicle.id} is ${label}.`, 'ST', 'teal'); }
document.querySelector('#evacuateBtn').addEventListener('click', () => { const source = incidents.find((item) => item.id === document.querySelector('#evacuationSource').value); const shelter = shelterIncident(); const selected = document.querySelector('#evacuationCount').value; const amount = selected === 'All remaining' ? source.people || 0 : Math.min(Number(selected), source.people || 0); if (!amount) return; source.people = Math.max(0, (source.people || 0) - amount); shelter.people = Math.min(shelter.capacity, shelter.people + amount); source.detail = source.people ? `Water rising · ${source.people} people awaiting transport` : 'Scene cleared · all civilians transported'; renderIncidents(); updateOperationsBoard(); addActivity('People moved to shelter', `${amount} people transported from ${source.title} to ${shelter.title}. Shelter now at ${shelter.people} of ${shelter.capacity}.`, 'ST', 'teal'); });
document.querySelector('#sendSceneBtn').addEventListener('click', () => { const incident = incidents.find((item) => item.id === document.querySelector('#movementDestination').value); moveUnit(incident.coords, `moving to ${incident.title}`); });
document.querySelector('#returnStagingBtn').addEventListener('click', () => moveUnit([30.440, -91.160], 'returning to Shelter East staging'));
document.querySelector('#saveTrappedBtn').addEventListener('click', () => { const collapse = incidents.find((item) => item.id === 'INC-041'); collapse.people = Math.max(0, Number(document.querySelector('#trappedCount').value) || 0); collapse.detail = `Access blocked · ${collapse.people} people trapped`; renderIncidents(); addActivity('Instructor updated trapped count', `${collapse.people} people trapped at ${collapse.title}.`, 'JM', 'coral'); });
document.querySelector('#transportPatientBtn').addEventListener('click', () => { const collapse = incidents.find((item) => item.id === 'INC-041'); const shelter = shelterIncident(); if (!collapse.people) return; collapse.people -= 1; shelter.people = Math.min(shelter.capacity, shelter.people + 1); collapse.detail = collapse.people ? `Access blocked · ${collapse.people} people trapped` : 'Access cleared · no trapped people remaining'; renderIncidents(); addActivity('EMS transported 1 patient', `One patient moved from ${collapse.title} to ${shelter.title}. ${collapse.people} people remain trapped.`, 'JM', 'coral'); });
document.querySelector('#postUpdateBtn').addEventListener('click', () => { const incident = incidents.find((item) => item.id === document.querySelector('#updateDestination').value); const status = document.querySelector('#updateStatus').value; const note = document.querySelector('#instructorNote').value.trim() || `Conditions ${status.toLowerCase()} at the scene.`; incident.status = status; incident.detail = note; if (status === 'RESOLVED') { renderIncidents(); } else { const card = list.querySelector(`[data-id="${incident.id}"]`); card.querySelector('.status').textContent = status; card.querySelector('p').textContent = note; markers[incident.id].setPopupContent(`<strong>${incident.id}</strong><br>${incident.title}<br><small>${note}</small>`); } addActivity('Instructor updated ' + incident.title, `${status}: ${note}`); document.querySelector('#instructorNote').value = ''; });
document.querySelector('#requestBtn').addEventListener('click', () => { const unit = document.querySelector('#requestUnit').value; const amount = document.querySelector('#requestAmount').value; const incident = incidents.find((item) => item.id === document.querySelector('#unitDestination').value); const note = document.querySelector('#requestNote').value.trim() || 'Additional support requested at the scene.'; addActivity('Student requested support', `${amount} ${unit} requested for ${incident.title}. ${note}`, 'ST', 'teal'); document.querySelector('#requestNote').value = ''; });
document.querySelector('#sendAlertBtn').addEventListener('click', sendAdminAlert);
const templatePrefix = 'PRE-TXT: ';
function loadSavedTemplates(storageKey) { try { return JSON.parse(localStorage.getItem(storageKey) || '[]'); } catch (error) { return []; } }
function saveTemplates(storageKey, templates) { localStorage.setItem(storageKey, JSON.stringify(templates)); }
function addTemplateOption(select, templateText) { if (!select || !templateText) return; const exists = [...select.options].some((option) => option.value === templateText); if (exists) return; const option = document.createElement('option'); option.value = templateText; option.textContent = templateText; select.append(option); }
function hydrateTemplates(select, storageKey) { loadSavedTemplates(storageKey).forEach((templateText) => addTemplateOption(select, templateText)); }
function saveCurrentFieldAsTemplate(fieldSelector, selectSelector, storageKey) { const field = document.querySelector(fieldSelector); const select = document.querySelector(selectSelector); if (!field || !select) return; const rawText = field.value.trim(); if (!rawText) return; const templateText = rawText.startsWith(templatePrefix) ? rawText.slice(templatePrefix.length) : rawText; const templates = loadSavedTemplates(storageKey); if (!templates.includes(templateText)) { templates.unshift(templateText); saveTemplates(storageKey, templates); addTemplateOption(select, templateText); } select.value = templateText; }
const alertTemplateStyles = document.createElement('style');
alertTemplateStyles.textContent = '.template-actions{margin:8px 0 12px}.template-save{display:inline-flex;align-items:center;justify-content:center;border:1px solid var(--teal);background:#eef6f3;color:var(--teal);padding:8px 10px;font-size:9px;font-weight:700;letter-spacing:.6px;cursor:pointer;border-radius:3px}.template-save:hover{background:#e2f1ed}';
document.head.append(alertTemplateStyles);
document.querySelector('#alertTemplate')?.addEventListener('change', (event) => {
  const template = event.target.value;
  if (template) {
    document.querySelector('#alertMessage').value = templatePrefix + template;
  }
});
document.querySelector('#dispatchTemplate')?.addEventListener('change', (event) => {
  const template = event.target.value;
  if (template) {
    document.querySelector('#dispatchInput').value = templatePrefix + template;
  }
});
hydrateTemplates(document.querySelector('#alertTemplate'), 'alertTemplates');
document.querySelector('#saveAlertTemplateBtn')?.addEventListener('click', () => saveCurrentFieldAsTemplate('#alertMessage', '#alertTemplate', 'alertTemplates'));
document.querySelectorAll('#memberSearch,#certFilter,#availabilityFilter').forEach((control) => control.addEventListener('input', renderCertifications));
document.querySelector('#certificationList').addEventListener('click', (event) => { const availabilityButton = event.target.closest('.availability-button'); const renewButton = event.target.closest('.renew-cert'); if (availabilityButton) { const member = members.find((item) => item.name === availabilityButton.dataset.member); member.availability = member.availability === 'available' ? 'unavailable' : 'available'; renderCertifications(); addActivity('Member availability updated', `${member.name} is now ${member.availability}.`, 'AD', 'teal'); } if (renewButton) { const member = members.find((item) => item.name === renewButton.dataset.member); const expiry = new Date(member.expires); expiry.setFullYear(expiry.getFullYear() + 1); member.expires = expiry.toISOString().slice(0, 10); renderCertifications(); addActivity('Certification renewed', `${member.name} · ${member.cert} renewed through ${member.expires}.`, 'AD', 'teal'); } });
let selectedUnit = 'USAR';
document.querySelectorAll('.unit-type').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.unit-type').forEach((item) => item.classList.remove('selected')); button.classList.add('selected'); selectedUnit = button.dataset.unit; }));
document.querySelector('#assignBtn').addEventListener('click', () => { const destination = document.querySelector('#unitDestination'); const teamSize = document.querySelector('#teamSize').value; const incident = incidents.find((item) => item.id === destination.value); const item = document.createElement('article'); item.className = 'activity-item'; item.innerHTML = `<span class="activity-avatar teal">ST</span><div><p><strong>Student team</strong> dispatched ${teamSize} ${selectedUnit}</p><small>Just now · ${incident.id}</small><div class="activity-note">${selectedUnit} en route to ${incident.title}.</div></div>`; feed.prepend(item); L.marker(incident.coords, { icon: markerIcon('resource') }).addTo(map).bindPopup(`<strong>${selectedUnit}</strong><br>En route to ${incident.title}`, { autoPan: false }).openPopup(); });
document.querySelectorAll('[data-role]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-role]').forEach((item) => item.classList.remove('active')); button.classList.add('active'); const isStudent = button.dataset.role === 'student'; unitDispatch.hidden = !isStudent; studentRequest.hidden = !isStudent; unitMovement.hidden = !isStudent; instructorControls.hidden = isStudent; document.querySelector('.briefing-card p').textContent = isStudent ? 'Select an incident to review its objectives, then acknowledge your team dispatch.' : 'Move teams through the flood corridor. Keep the east shelter below 80% capacity.'; }));
document.querySelector('#sendBtn').addEventListener('click', () => { const input = document.querySelector('#dispatchInput'); const text = input.value.trim(); if (!text) return; const item = document.createElement('article'); item.className = 'activity-item'; item.innerHTML = `<span class="activity-avatar coral">JM</span><div><p><strong>Jules Morgan</strong> sent a dispatch</p><small>Just now · All teams</small><div class="activity-note">${text.replace(/[<>]/g, '')}</div></div>`; feed.prepend(item); input.value = ''; });
document.querySelector('#templateBtn')?.addEventListener('click', () => { document.querySelector('[data-view="admin"]')?.click(); document.querySelector('#alertTemplate')?.focus(); });
document.querySelector('#recenterBtn').addEventListener('click', () => map.flyTo([30.451, -91.180], 14, { duration: .6 }));
document.querySelector('#locateBtn').addEventListener('click', () => { if (navigator.geolocation) navigator.geolocation.getCurrentPosition((position) => map.flyTo([position.coords.latitude, position.coords.longitude], 15)); });
setInterval(() => { document.querySelector('#clock').textContent = new Date().toLocaleTimeString('en-US', { hour12: false }); }, 1000);
let remaining = 5272; setInterval(() => { remaining = Math.max(0, remaining - 1); const h = String(Math.floor(remaining / 3600)).padStart(2, '0'); const m = String(Math.floor(remaining % 3600 / 60)).padStart(2, '0'); const s = String(remaining % 60).padStart(2, '0'); document.querySelector('#countdown').textContent = `${h}:${m}:${s}`; }, 1000);
document.querySelectorAll('[data-view]').forEach((tab) => tab.addEventListener('click', () => { document.querySelectorAll('[data-view]').forEach((item) => item.classList.remove('active')); tab.classList.add('active'); const commandView = tab.dataset.view === 'command'; const adminView = tab.dataset.view === 'admin'; document.querySelector('#commandBoard').hidden = !commandView; document.querySelector('#adminBoard').hidden = !adminView; document.querySelector('#mapWorkspace').hidden = commandView || adminView; }));
renderCertifications();
renderReplies();
updateOperationsBoard();
